// Espécie
export enum Especie {
  GATO = 'Gato',
  CACHORRO = 'Cachorro',
  AVE = 'Ave',
  ROEDOR = 'Roedor',
}

// Pelagem
export enum Pelagem {
  AMARELA = 'Amarela',
  BICOLOR = 'Bicolor',
  BRANCA = 'Branca',
  CARAMELO = 'Caramelo',
  CINZA = 'Cinza',
  LARANJA = 'Laranja',
  MALHADA = 'Malhada',
  MARROM = 'Marrom',
  MESCLADA = 'Mesclada',
  PRETA = 'Preta',
  TIGRADA = 'Tigrada',
  TRICOLOR = 'Tricolor',
}

// Temperamento
export enum Temperamento {
  AGITADO = 'Agitado',
  AGRESSIVO = 'Agressivo',
  BRAVO = 'Bravo',
  BRINCALHÃO = 'Brincalhão',
  CALMO = 'Calmo',
  CARINHOSO = 'Carinhoso',
  INDEPENDENTE = 'Independente',
  MEDROSO = 'Medroso',
  PROTETOR = 'Protetor',
  SOCIÁVEL = 'Sociável',
}

// Raça vinculada à espécie
export interface Raca {
  especie: Especie;
  nome: string;
}

export const Racas: Raca[] = [
  { especie: Especie.GATO, nome: 'Abissínio' },
  { especie: Especie.GATO, nome: 'Angorá turco' },
  { especie: Especie.GATO, nome: 'Asiático de pelo semilongo' },
  { especie: Especie.GATO, nome: 'Azul Russo' },
  { especie: Especie.GATO, nome: 'Balinês' },
  { especie: Especie.GATO, nome: 'Bambino' },
  { especie: Especie.GATO, nome: 'Bicolor Oriental' },
  { especie: Especie.GATO, nome: 'Bobtail americano' },
  { especie: Especie.GATO, nome: 'Bobtail japonês' },
  { especie: Especie.GATO, nome: 'Bombaim' },
  { especie: Especie.GATO, nome: 'Burmês' },
  { especie: Especie.GATO, nome: 'Burmila' },
  { especie: Especie.GATO, nome: 'California Spangled' },
  { especie: Especie.GATO, nome: 'Cingapura' },
  { especie: Especie.GATO, nome: 'Chartreux' },
  { especie: Especie.GATO, nome: 'Chausie' },
  { especie: Especie.GATO, nome: 'Colorpoint de pelo curto' },
  { especie: Especie.GATO, nome: 'Cornish Rex' },
  { especie: Especie.GATO, nome: 'Curl Americano' },
  { especie: Especie.GATO, nome: 'Devon Rex' },
  { especie: Especie.GATO, nome: 'Donskoy' },
  { especie: Especie.GATO, nome: 'Dragon Li' },
  { especie: Especie.GATO, nome: 'Egeu' },
  { especie: Especie.GATO, nome: 'Gato-de-Bengala' },
  { especie: Especie.GATO, nome: 'Gato do Chipre' },
  { especie: Especie.GATO, nome: 'Exótico' },
  { especie: Especie.GATO, nome: 'Gato asiático' },
  { especie: Especie.GATO, nome: 'Gato Siberiano' },
  { especie: Especie.GATO, nome: 'Havana marrom' },
  { especie: Especie.GATO, nome: 'Himalaio' },
  { especie: Especie.GATO, nome: 'Javanês' },
  { especie: Especie.GATO, nome: 'Korat' },
  { especie: Especie.GATO, nome: 'Khao Manee' },
  { especie: Especie.GATO, nome: 'Kurilian Bobtail' },
  { especie: Especie.GATO, nome: 'LaPerml' },
  { especie: Especie.GATO, nome: 'Levkoy ucraniano' },
  { especie: Especie.GATO, nome: 'Lykoi' },
  { especie: Especie.GATO, nome: 'Maine Coon' },
  { especie: Especie.GATO, nome: 'Manx' },
  { especie: Especie.GATO, nome: 'Manx de pelo longo' },
  { especie: Especie.GATO, nome: 'Mau Árabe' },
  { especie: Especie.GATO, nome: 'Mau egípcio' },
  { especie: Especie.GATO, nome: 'Minskin' },
  { especie: Especie.GATO, nome: 'Mist Australiano' },
  { especie: Especie.GATO, nome: 'Munchkin' },
  { especie: Especie.GATO, nome: 'Nebelung' },
  { especie: Especie.GATO, nome: 'Norueguês da Floresta' },
  { especie: Especie.GATO, nome: 'Ocicat' },
  { especie: Especie.GATO, nome: 'Ojos Azules' },
  { especie: Especie.GATO, nome: 'Oregon Rex' },
  { especie: Especie.GATO, nome: 'Pelo curto americano' },
  { especie: Especie.GATO, nome: 'Pelo curto brasileiro' },
  { especie: Especie.GATO, nome: 'Pelo curto Europeu' },
  { especie: Especie.GATO, nome: 'Pelo curto inglês' },
  { especie: Especie.GATO, nome: 'Pelo longo Inglês' },
  { especie: Especie.GATO, nome: 'Pelo curto Oriental' },
  { especie: Especie.GATO, nome: 'Pelo longo Oriental' },
  { especie: Especie.GATO, nome: 'Persa' },
  { especie: Especie.GATO, nome: 'Peterbald' },
  { especie: Especie.GATO, nome: 'Pixie-bob' },
  { especie: Especie.GATO, nome: 'Raas' },
  { especie: Especie.GATO, nome: 'Ragamuffin' },
  { especie: Especie.GATO, nome: 'Ragdoll' },
  { especie: Especie.GATO, nome: 'Rex Alemão' },
  { especie: Especie.GATO, nome: 'Sagrado da Birmânia' },
  { especie: Especie.GATO, nome: 'Savannah' },
  { especie: Especie.GATO, nome: 'Scottish Fold' },
  { especie: Especie.GATO, nome: 'Selkirk Rex' },
  { especie: Especie.GATO, nome: 'Serengeti' },
  { especie: Especie.GATO, nome: 'Siamês' },
  { especie: Especie.GATO, nome: 'Singapura' },
  { especie: Especie.GATO, nome: 'Snowshoe' },
  { especie: Especie.GATO, nome: 'Sokoke' },
  { especie: Especie.GATO, nome: 'Somali' },
  { especie: Especie.GATO, nome: 'Sphynx' },
  { especie: Especie.GATO, nome: 'SRD' },
  { especie: Especie.GATO, nome: 'Suphalak' },
  { especie: Especie.GATO, nome: 'Thai' },
  { especie: Especie.GATO, nome: 'Tiffany-Chantilly' },
  { especie: Especie.GATO, nome: 'Tonquinês' },
  { especie: Especie.GATO, nome: 'Toyger' },
  { especie: Especie.GATO, nome: 'Van Turco' },
  { especie: Especie.GATO, nome: 'Wirehair Americano' },

  { especie: Especie.CACHORRO, nome: 'Akita' },
  { especie: Especie.CACHORRO, nome: 'Basset hound' },
  { especie: Especie.CACHORRO, nome: 'Beagle' },
  { especie: Especie.CACHORRO, nome: 'Bichon frisé' },
  { especie: Especie.CACHORRO, nome: 'Boiadeiro australiano' },
  { especie: Especie.CACHORRO, nome: 'Border collie' },
  { especie: Especie.CACHORRO, nome: 'Boston terrier' },
  { especie: Especie.CACHORRO, nome: 'Boxer' },
  { especie: Especie.CACHORRO, nome: 'Buldogue francês' },
  { especie: Especie.CACHORRO, nome: 'Buldogue inglês' },
  { especie: Especie.CACHORRO, nome: 'Bull terrier' },
  { especie: Especie.CACHORRO, nome: 'Cane corso' },
  { especie: Especie.CACHORRO, nome: 'Cavalier king charles spaniel' },
  { especie: Especie.CACHORRO, nome: 'Chihuahua' },
  { especie: Especie.CACHORRO, nome: 'Chow chow' },
  { especie: Especie.CACHORRO, nome: 'Cocker spaniel inglês' },
  { especie: Especie.CACHORRO, nome: 'Dachshund' },
  { especie: Especie.CACHORRO, nome: 'Dálmata' },
  { especie: Especie.CACHORRO, nome: 'Doberman' },
  { especie: Especie.CACHORRO, nome: 'Dogo argentino' },
  { especie: Especie.CACHORRO, nome: 'Dogue alemão' },
  { especie: Especie.CACHORRO, nome: 'Fila brasileiro' },
  { especie: Especie.CACHORRO, nome: 'Golden retriever' },
  { especie: Especie.CACHORRO, nome: 'Husky siberiano' },
  { especie: Especie.CACHORRO, nome: 'Jack russell terrier' },
  { especie: Especie.CACHORRO, nome: 'Labrador retriever' },
  { especie: Especie.CACHORRO, nome: 'Lhasa apso' },
  { especie: Especie.CACHORRO, nome: 'Lulu da pomerânia' },
  { especie: Especie.CACHORRO, nome: 'Maltês' },
  { especie: Especie.CACHORRO, nome: 'Mastiff inglês' },
  { especie: Especie.CACHORRO, nome: 'Mastim tibetano' },
  { especie: Especie.CACHORRO, nome: 'Pastor alemão' },
  { especie: Especie.CACHORRO, nome: 'Pastor australiano' },
  { especie: Especie.CACHORRO, nome: 'Pastor de Shetland' },
  { especie: Especie.CACHORRO, nome: 'Pequinês' },
  { especie: Especie.CACHORRO, nome: 'Pinscher' },
  { especie: Especie.CACHORRO, nome: 'Pit bull' },
  { especie: Especie.CACHORRO, nome: 'Poodle' },
  { especie: Especie.CACHORRO, nome: 'Pug' },
  { especie: Especie.CACHORRO, nome: 'Rottweiler' },
  { especie: Especie.CACHORRO, nome: 'Schnauzer' },
  { especie: Especie.CACHORRO, nome: 'Shar-pei' },
  { especie: Especie.CACHORRO, nome: 'Shiba' },
  { especie: Especie.CACHORRO, nome: 'Shih tzu' },
  { especie: Especie.CACHORRO, nome: 'Staffordshire bull terrier' },
  { especie: Especie.CACHORRO, nome: 'Weimaraner' },
  { especie: Especie.CACHORRO, nome: 'Yorkshire' },
  { especie: Especie.CACHORRO, nome: 'SRD' },

  { especie: Especie.AVE, nome: 'Calopsita' },
  { especie: Especie.AVE, nome: 'Papagaio' },

  { especie: Especie.ROEDOR, nome: 'Hamster' },
  { especie: Especie.ROEDOR, nome: 'Porquinho-da-Índia' },
];

// Função utilitária para filtrar raças por espécie
export function getRacasPorEspecie(especie: Especie): string[] {
  return Racas.filter((r) => r.especie === especie).map((r) => r.nome);
}
